### PR TITLE
tp partime inital pr

### PR DESCRIPTION
**Pull request by gavin24**

### CODE REVIEW

**Comment by boniface** [comment]
Rejected , has conflict. Fix the Conflict

**Comment by boniface** [comment]
Conflicting files
app/domain/job/JobEvent.scala
app/factories/job/JobEventFactory.scala
build.sbt

**Comment by boniface** [comment]
Fix Conflicts-Rejected

**Comment by gavin24** [comment]
i let the group know, they're still busy i'll pr as soon as they're done.

**Pull request closed without merging**
